Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-07, with the labels that each got.

#713 feat: expandItems (v2)
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
  src/components/ItaliaTheme/manage/Widgets/SearchSectionsConfigurationWidget/SearchSectionsConfigurationForm.jsx
Labels: enhancement, v2

#726 feat: add pagination to cards listings in Venue, refactor pagination logic into custom hook
  RELEASE.md
  src/components/ItaliaTheme/Pagination/Pagination.jsx
  src/components/ItaliaTheme/View/Commons/RelatedArticles.jsx
  src/components/ItaliaTheme/View/UOView/UOServices.jsx
  src/helpers/index.js
  src/helpers/usePaginatedItemsSection.hook.ts
Labels: enhancement

#725 fix: set maxFileUploadSize config setting to 100mb
  RELEASE.md
  src/config/italiaConfig.js
Labels: bug

#729 fix: fixed list style format in sidebar context and TextSize icon
  src/config/RichTextEditor/ToolbarButtons/TextSizeButton.jsx
  theme/_cms-ui.scss
Labels: v2
