Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-03, with the labels that each got.

#561 rich text has content
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/IconBlocks/Sidebar.jsx
  src/components/ItaliaTheme/Blocks/IconBlocks/View.jsx
Labels: bug

#552 fix: better alt text for nexGenerationEU logo
  RELEASE.md
  src/components/ItaliaTheme/Footer/FooterPNRRLogo.jsx
Labels: a11y-accessibility

#554 fix: removed unnecessary special character from HeaderToggler aria-controls attribute
  RELEASE.md
  src/customizations/volto/components/theme/Navigation/Navigation.jsx
Labels: a11y-accessibility, v2

#558 Us 50642 50641 title attr card w img
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx
  src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
  src/components/ItaliaTheme/Cards/CardPersona.jsx
Labels: a11y-accessibility

#559 fix: remove title attribute in WideImage component
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/WideImage.jsx
Labels: a11y-accessibility

#560 Us 51248 accessibilita customer satisfaction
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
  src/components/ItaliaTheme/CustomerSatisfaction/Steps/AnswersStep.jsx
  src/components/ItaliaTheme/CustomerSatisfaction/Steps/CommentsStep.jsx
  src/components/ItaliaTheme/CustomerSatisfaction/Steps/Commons/Rating.jsx
  src/customizations/volto-feedback/components/FeedbackForm/Steps/Commons.jsx
  src/theme/ItaliaTheme/Components/_customerSatisfaction.scss
Labels: a11y-accessibility

#563 fix: added returnUrl option for came_from parameter
  RELEASE.md
  src/customizations/volto/components/theme/Login/Login.jsx
Labels: v2

#542 fix: added class to apply color style to all icons
  RELEASE.md
  src/theme/ItaliaTheme/Components/_mobileMenu.scss
Labels: a11y-accessibility

#575 fix: customer satisfaction per validatore pa
  src/customizations/volto-feedback/components/FeedbackForm/Steps/Commons.jsx
Labels: pa-validator

#528 Us 44477 editable footer top
  RELEASE.md
  jest-addon.config.js
  package.json
  src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
  src/components/ItaliaTheme/CustomerSatisfaction/Steps/CommentsStep.jsx
  src/components/ItaliaTheme/Footer/FooterMain.jsx
  src/theme/ItaliaTheme/Blocks/_cardWithImageAndInEvidence.scss
  src/theme/ItaliaTheme/Blocks/_ribbonCardTemplate.scss
  src/theme/ItaliaTheme/Blocks/_simpleCardTemplate.scss
  src/theme/ItaliaTheme/Components/_card.scss
  src/theme/ItaliaTheme/Subsites/ItaliaTheme/Views/_common.scss
  src/theme/ItaliaTheme/Subsites/ItaliaTheme/Widgets/reactSelect.scss
  src/theme/ItaliaTheme/Subsites/bootstrap-italia/custom/_navigation.scss
  src/theme/ItaliaTheme/_main.scss
  yarn.lock
Labels: rer

#573 feat: TextWidget to add alt text to image
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Block.jsx
  src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Sidebar.jsx
Labels: a11y-accessibility

#585 fix: collapse button alignment for filters in Search page
  RELEASE.md
  theme/ItaliaTheme/Components/_search.scss
Labels: v2

#589 fix: changed accessible labels for customer satisfaction
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/CustomerSatisfaction/CustomerSatisfaction.jsx
Labels: a11y-accessibility, v2

#595 fix: added aria-hidden attribute to icons
  RELEASE.md
  src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
  src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
Labels: a11y-accessibility, v2

#609 General background color for icons block
  theme/ItaliaTheme/Subsites/ItaliaTheme/Blocks/_iconBlocks.scss
  theme/ItaliaTheme/Subsites/_mixin.scss
Labels: v2

#611 fix: added role='button' to search link
  RELEASE.md
  src/components/ItaliaTheme/Header/HeaderSearch/HeaderSearch.jsx
Labels: a11y-accessibility

#612 fix: added role='button' to search link
  RELEASE.md
  src/components/ItaliaTheme/Header/HeaderSearch/HeaderSearch.jsx
Labels: a11y-accessibility, v2

#617 fix: alt defaults to item.title for ListingImages for accessibility
  src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx
  src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
Labels: a11y-accessibility

#620 fix: aria-label in calendar block controls
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
Labels: a11y-accessibility

#557 fix: added aria label to icons across ioComune
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/Accordion/Block/ViewBlock.jsx
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/DateFilter.jsx
  src/components/ItaliaTheme/Blocks/HeroImageLeft/StoresButtons.jsx
  src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx
  src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
  src/components/ItaliaTheme/Blocks/NumbersBlock/View.jsx
  src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx
  src/components/ItaliaTheme/Blocks/VideoGallery/Body.jsx
  src/components/ItaliaTheme/Cards/CardCategory.jsx
  src/components/ItaliaTheme/Footer/FooterNavigation.jsx
  src/components/ItaliaTheme/Footer/FooterSocials.jsx
  src/components/ItaliaTheme/Header/HeaderSearch/HeaderSearch.jsx
  src/components/ItaliaTheme/Header/SocialHeader.jsx
  src/components/ItaliaTheme/Icons/DesignIcon.jsx
  src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
  src/components/ItaliaTheme/Icons/Icon.jsx
  src/components/ItaliaTheme/Icons/svg/TelegramSVG.jsx
  src/components/ItaliaTheme/Icons/svg/XTwitterSVG.jsx
  src/components/ItaliaTheme/Pagination/PaginationItem.jsx
  src/components/ItaliaTheme/View/Commons/Argument/ArgumentIcon.jsx
  src/components/ItaliaTheme/View/Commons/HelpBox.jsx
  src/components/ItaliaTheme/View/Commons/LocationItem.jsx
  src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
  src/components/ItaliaTheme/View/Commons/SearchSectionForm.jsx
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
  src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx
  src/components/SelectInput/SelectInput.jsx
  src/customizations/volto-form-block/components/Field.jsx
  src/customizations/volto/components/manage/Blocks/Search/components/DateRangeFacet.jsx
  src/customizations/volto/components/theme/Navigation/Navigation.jsx
Labels: a11y-accessibility
