Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-10, with the labels that each got.

#741 Widget ricorrenza multifix
  RELEASE.md
  src/customizations/volto/components/manage/Diff/DiffField.jsx
  src/customizations/volto/components/manage/Widgets/RecurrenceWidget/EndField.jsx
  src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
Labels: bug, enhancement, help wanted

#785 fix: changed double focus to outline and box-shadow
  src/theme/ItaliaTheme/Blocks/common/_searchBlockFilters.scss
  src/theme/ItaliaTheme/Widgets/_reactSelect.scss
  src/theme/ItaliaTheme/_common.scss
  src/theme/_site-variables.scss
  src/theme/bootstrap-override/bootstrap-italia/_focus.scss
  src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss
Labels: a11y-accessibility

#786 Do not break LinkView for anonymous users
  src/customizations/volto/components/theme/View/LinkView.jsx
Labels: bug

#795 feat: date validity in Alert block
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/Alert/AlertWrapper.jsx
  src/components/ItaliaTheme/Blocks/Alert/Edit.jsx
  src/components/ItaliaTheme/Blocks/Alert/Sidebar.jsx
  src/components/ItaliaTheme/Blocks/Alert/View.jsx
  theme/ItaliaTheme/Blocks/_alert.scss
Labels: enhancement, v2
