Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-04, with the labels that each got.

#628 fix: remove icon from Organizzatori eventi card
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreInterno.jsx
Labels: bug

#622 fix: translation id typo
  src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
Labels: a11y-accessibility

#591 fix: translated aria-label of menu hamburger icon
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/customizations/volto/components/theme/Navigation/Navigation.jsx
  src/overrideTranslations.jsx
Labels: a11y-accessibility

#592 fix: translated aria-label of menu hamburger icon
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/customizations/volto/components/theme/Navigation/Navigation.jsx
  src/overrideTranslations.jsx
Labels: a11y-accessibility, v2

#618 fix: added aria-label for cardReadMore component in iconBlock
  src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
Labels: a11y-accessibility

#636 trackFocus
  src/components/ItaliaTheme/AppExtras/TrackFocus.jsx
  src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx
  src/components/ItaliaTheme/MenuSecondary/MenuSecondary.jsx
  src/config/italiaConfig.js
  theme/ItaliaTheme/Components/_navigation.scss
  theme/site.scss
Labels: v2

#641 Us 53982 identificazione elementi
  RELEASE.md
  src/components/ItaliaTheme/Footer/FooterNavigation.jsx
Labels: a11y-accessibility

#639 fix: sitemap in multilingual sites was erroring, volto bug, fixed
  RELEASE.md
  src/customizations/volto/components/manage/Blocks/Search/components/SelectFacetFilterListEntry.jsx
  src/customizations/volto/components/theme/Sitemap/Sitemap.jsx
Labels: bug

#638 fix: remove exdates from additionalDates in recurrences for ct Event
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/Dates.jsx
Labels: bug

#637 fix: card servizi same height in ct UO
  src/components/ItaliaTheme/View/UOView/UOServices.jsx
Labels: enhancement

#653 fix: changed aria-hidden to false
  RELEASE.md
  src/components/ItaliaTheme/Slider/NextArrow.jsx
  src/components/ItaliaTheme/Slider/PrevArrow.jsx
Labels: a11y-accessibility

#667 fix: add event start date for subevents that do not have an image
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/Events.jsx
Labels: enhancement
