Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-09, with the labels that each got.

#749 feat: Last modified document
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/View/BandoView/BandoApprofondimenti.jsx
  src/components/ItaliaTheme/View/Commons/Attachment.jsx
Labels: v2

#747 feat: video gallery option for caption
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/VideoGallery/Block/EditBlock.jsx
  src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
  src/components/ItaliaTheme/Blocks/VideoGallery/Edit.jsx
  src/components/ItaliaTheme/Blocks/VideoGallery/Sidebar.jsx
  src/components/ItaliaTheme/Blocks/VideoGallery/View.jsx
Labels: v2

#760 fix: added caption to youtube videos
  src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
Labels: v2

#765 feat: title and description for block accordion - v11
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
  src/components/ItaliaTheme/Blocks/Accordion/View.jsx
  src/theme/ItaliaTheme/Blocks/_accordion.scss
Labels: enhancement

#768 fix: added autocomplete attribute in search and customer satisfaction fields - mauve
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/TextFilter.jsx
  src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx
  src/components/ItaliaTheme/CustomerSatisfaction/Steps/AnswersStep.jsx
  src/components/ItaliaTheme/CustomerSatisfaction/Steps/CommentsStep.jsx
Labels: a11y-accessibility

#766 feat: title and description added to accordion block - v12
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
  src/components/ItaliaTheme/Blocks/Accordion/View.jsx
  src/theme/ItaliaTheme/Blocks/_accordion.scss
Labels: enhancement

#771 fix: added block id to date ids to ensure unique field ids
  src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/DateFilter.jsx
  src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
Labels: a11y-accessibility

#775 fix/refactor: resolve bug in the video gallery block doing a refactor code structure
  RELEASE.md
  src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
  yarn.lock
Labels: bug, v2

#770 fix: used p with h classname to ensure correct heading order
  src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/BottomBody.jsx
  src/components/ItaliaTheme/Footer/FooterInfos.jsx
  src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx
  src/components/ItaliaTheme/View/Commons/RelatedItems.jsx
  src/components/ItaliaTheme/View/Commons/SideMenu.jsx
  src/components/ItaliaTheme/View/PuntoDiContattoView/PuntoDiContattoView.jsx
  src/components/ItaliaTheme/View/VenueView/VenueWhere.jsx
Labels: a11y-accessibility

#772 fix: changed focus color
  RELEASE.md
  src/theme/ItaliaTheme/Addons/volto-gdpr-privacy.scss
  src/theme/ItaliaTheme/Blocks/common/_searchBlockFilters.scss
  src/theme/ItaliaTheme/Widgets/_reactSelect.scss
  src/theme/ItaliaTheme/_common.scss
  src/theme/_site-variables.scss
  src/theme/bootstrap-override/bootstrap-italia/_focus.scss
  src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss
Labels: a11y-accessibility

#776 fix: added condition for spid user link redirect
  RELEASE.md
  src/customizations/volto/components/theme/View/LinkView.jsx
Labels: enhancement
