Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-11, with the labels that each got.

#804 fix: removed class Block from Alert block View
  src/components/ItaliaTheme/Blocks/Alert/View.jsx
Labels: bug

#810 Bug 60364 universal link safari and lazy icons
  RELEASE.md
  src/components/ItaliaTheme/Icons/DesignIcon.jsx
  src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
  src/components/ItaliaTheme/Icons/Icon.jsx
  src/theme/ItaliaTheme/_main.scss
Labels: bug

#803 Us 55252 remove get content from view components
  src/components/ItaliaTheme/View/BandoView/BandoApprofondimenti.jsx
  src/components/ItaliaTheme/View/Commons/LocationsMap.jsx
  src/components/ItaliaTheme/View/Commons/Module.jsx
  src/components/ItaliaTheme/View/Commons/Modules.jsx
  src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx
Labels: pending-review

#800 fix: removed whole day condition in page header subtitle
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx
Labels: to-be-merged, waiting-be

#801 fix: removed whole day condition in page header subtitle
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx
Labels: to-be-merged, waiting-be

#811 Bug 60364 universal link safari and lazy icons slate
  RELEASE.md
  src/components/ItaliaTheme/Icons/DesignIcon.jsx
  src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx
  src/theme/ItaliaTheme/_main.scss
Labels: bug

#815 feat: added checkbox for showing image for all cards in eventsSearch
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
  src/components/ItaliaTheme/Blocks/EventSearch/Sidebar.jsx
  src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
  src/components/ItaliaTheme/Blocks/UOSearch/Sidebar.jsx
Labels: to-be-merged

#816 feat: added checkbox for showing image for all cards in uo search - main
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
  src/components/ItaliaTheme/Blocks/EventSearch/Sidebar.jsx
  src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
  src/components/ItaliaTheme/Blocks/UOSearch/Sidebar.jsx
Labels: to-be-merged

#817 feat: added cardCalendar in children events for rassegne
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/Events.jsx
Labels: to-be-merged
