Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2024-02, with the labels that each got.

#514 Simple card title changed from h4 to h3
  RELEASE.md
  src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/Block.jsx
Labels: a11y-accessibility

#526 fix: do not show empty headings if title in block is not configured
  RELEASE.md
  src/components/ItaliaTheme/Blocks/CountDown/Body.jsx
  src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx
Labels: a11y-accessibility, v2

#518 fix: better a11y for social links
  RELEASE.md
  src/components/ItaliaTheme/Header/SocialHeader.jsx
Labels: a11y-accessibility

#521 fix: fixed semantic headings levels in rss templates, all h3 now
  RELEASE.md
  src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
  src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
  src/components/ItaliaTheme/Blocks/RssBlock/TemplatesSkeleton/CardWithImageRssTemplateSkeleton.jsx
  src/components/ItaliaTheme/Blocks/RssBlock/TemplatesSkeleton/CardWithoutImageRssTemplateSkeleton.jsx
Labels: a11y-accessibility

#523 fix: fixed semantic headings levels in rss templates, all h3 now
  RELEASE.md
  src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
  src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
Labels: a11y-accessibility, v2

#520 fix: fix skip link go to content in site search page
  RELEASE.md
  src/components/ItaliaTheme/Search/Search.jsx
Labels: a11y-accessibility

#516 fix: better screen reader user experience in contacts, contact type i…
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/View/Commons/ContactsCard.jsx
  src/components/ItaliaTheme/View/PuntoDiContattoView/PuntoDiContattoView.jsx
  src/helpers/contentHelper.js
  src/theme/ItaliaTheme/Subsites/ItaliaTheme/Blocks/_highlitedContent.scss
  src/theme/ItaliaTheme/Subsites/ItaliaTheme/_common.scss
Labels: a11y-accessibility

#529 fix: fixed wrong date display for events that span on multiple years
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Listing/Commons/CardCalendar.jsx
Labels: bug

#532 fix: dates layout in CardWithImage template and 4 columns layout
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
  src/theme/ItaliaTheme/Blocks/_cardWithImageAndInEvidence.scss
Labels: bug
