Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-02, with the labels that each got.

#865 fix: changed styles of headings for text editor in cts
  RELEASE.md
  src/theme/ItaliaTheme/Widgets/_blocksWidget.scss
Labels: to-be-merged

#864 fix: changed styles of headings for text editor in cts
  RELEASE.md
  src/theme/ItaliaTheme/Widgets/_blocksWidget.scss
Labels: to-be-merged

#862 Us 64139 visualizzazione contatti
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/View/EventoView/EventoContatti.jsx
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreInterno.jsx
  src/components/ItaliaTheme/View/EventoView/EventoOrganizzatoDa.jsx
  src/components/ItaliaTheme/View/EventoView/EventoPatrocinatoDa.jsx
  src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx
Labels: to-be-merged

#863 fix: rearranged contacts section for events
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/View/EventoView/EventoContatti.jsx
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
  src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreInterno.jsx
  src/components/ItaliaTheme/View/EventoView/EventoOrganizzatoDa.jsx
  src/components/ItaliaTheme/View/EventoView/EventoPatrocinatoDa.jsx
  src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx
Labels: to-be-merged

#873 fix: grid block on mobile
  RELEASE.md
  src/theme/ItaliaTheme/Blocks/_gridBlock.scss
Labels: rer, to-be-merged, porting-needed

#868 fix: listing template attachments download and display file
  RELEASE.md
  locales/en/LC_MESSAGES/volto.po
  src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
  src/config/Blocks/ListingOptions/attachmentCardTemplate.js
  src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx
Labels: rer, porting-needed

#877 chore: Updated volto-venue to improve a11y and resume copyright
  package.json
  yarn.lock
Labels: rer, porting-needed

#875 fix: a11y of Contacts, Icons, and Numbers block
  RELEASE.md
  src/components/ItaliaTheme/Blocks/ContactsBlock/Block/EditBlock.jsx
  src/components/ItaliaTheme/Blocks/ContactsBlock/Edit.jsx
  src/components/ItaliaTheme/Blocks/IconBlocks/Block/EditBlock.jsx
  src/components/ItaliaTheme/Blocks/IconBlocks/Edit.jsx
  src/components/ItaliaTheme/Blocks/NumbersBlock/Block/EditBlock.jsx
  src/components/ItaliaTheme/Blocks/NumbersBlock/Edit.jsx
  src/theme/ItaliaTheme/Blocks/_accordion.scss
  src/theme/ItaliaTheme/Blocks/_contacts.scss
  src/theme/ItaliaTheme/Blocks/_ctaBlock.scss
  src/theme/ItaliaTheme/Blocks/_iconBlocks.scss
  src/theme/ItaliaTheme/Blocks/_numbers.scss
  src/theme/ItaliaTheme/Blocks/_subblocks-edit.scss
  src/theme/_mixins.scss
Labels: rer, porting-needed

#861 wip: fixing all image checks and ListingImage
  RELEASE.md
  src/components/ImageWithErrors/ImageWithErrors.jsx
  src/components/ItaliaTheme/Blocks/Listing/CardWithImage/CardWithImageDefault.jsx
  src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx
  src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/PhotogalleryTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/SmallBlockLinksTemplate.jsx
  src/components/ItaliaTheme/Cards/CardPersona.jsx
  src/components/ItaliaTheme/View/Commons/GenericCard.jsx
  src/components/ItaliaTheme/View/Commons/LocationItem.jsx
  src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
  src/components/ItaliaTheme/View/Commons/Sponsors.jsx
  src/components/ItaliaTheme/View/Commons/VenuesSmall.jsx
  src/customizations/volto/components/theme/View/ListingView.jsx
  src/helpers/images.js
  src/helpers/index.js
Labels: bug, pending-review, porting-needed

#876 fix: layout and style issues, customized bootstrap-italia/_avatar.scss due to nonsense scaling for avatar-lg sizes, figma compliant
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/LocationItem.jsx
  src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
  src/components/ItaliaTheme/View/Commons/VenuesSmall.jsx
  src/theme/ItaliaTheme/Components/_cardLocationItem.scss
  src/theme/bootstrap-override/_bootstrap-italia-site.scss
  src/theme/bootstrap-override/bootstrap-italia/_avatar.scss
Labels: porting-needed

#882 fix: rollback label selectinput
  RELEASE.md
  src/components/SelectInput/SelectInput.jsx
Labels: bug, rer

#881 fix: card persona fonts
  src/theme/ItaliaTheme/Blocks/_cardWithImage.scss
  src/theme/ItaliaTheme/Components/_cardPersona.scss
Labels: porting-needed

#860 fix: Landmaks a11y
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
  src/components/ItaliaTheme/Header/HeaderSearch/HeaderSearch.jsx
  src/components/ItaliaTheme/Header/HeaderSearch/SearchModal.jsx
  src/components/ItaliaTheme/Header/HeaderSlim/HeaderSlim.jsx
  src/components/ItaliaTheme/Header/HeaderSlim/TertiaryMenu.jsx
  src/components/ItaliaTheme/Header/ParentSiteMenu.jsx
  src/components/ItaliaTheme/SkipLinks/SkipLinks.jsx
  src/components/ItaliaTheme/View/BandoView/BandoView.jsx
  src/components/ItaliaTheme/View/Commons/RelatedItemInEvidence/RelatedItemInEvidence.jsx
  src/components/ItaliaTheme/View/Commons/RelatedItems.jsx
  src/components/ItaliaTheme/View/Commons/SideMenu.jsx
  src/components/ItaliaTheme/View/DocumentoView/DocumentoView.jsx
  src/components/ItaliaTheme/View/EventoView/EventoView.jsx
  src/components/ItaliaTheme/View/FAQ/FaqFolder/SearchBar.jsx
  src/components/ItaliaTheme/View/NewsItemView/NewsItemView.jsx
  src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoViewNoBlocks.jsx
  src/components/ItaliaTheme/View/PersonaView/PersonaView.jsx
  src/components/ItaliaTheme/View/ServizioView/ServizioView.jsx
  src/components/ItaliaTheme/View/UOView/UOView.jsx
  src/components/ItaliaTheme/View/VenueView/VenueView.jsx
  src/customizations/volto/components/theme/Navigation/Navigation.jsx
  src/overrideTranslations.jsx
Labels: a11y-accessibility, rer, porting-needed

#851 fix: added condition to set the listing image caption
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Listing/CardWithImage/CardWithImageDefault.jsx
  src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx
  src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
  src/components/ItaliaTheme/Cards/CardPersona.jsx
Labels: a11y-accessibility, rer, porting-needed

#878 fix: non backtracking regex
  src/customizations/volto/helpers/FormValidation/FormValidation.js
Labels: security

#883 fix: prevent scrollbars in select-facet of search block
  RELEASE.md
  src/theme/ItaliaTheme/Blocks/_search.scss
Labels: rer

#886 fix: render of nome_alternativo for Venue view
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/PageHeader/PageHeader.jsx
  src/components/ItaliaTheme/View/VenueView/VenueView.jsx
Labels: rer
