Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-01, with the labels that each got.

#852 fix: image with error on error loop, customizable fallback image in site properties
  src/components/ImageWithErrors/ImageWithErrors.jsx
  src/config/italiaConfig.js
  src/helpers/images.js
  src/helpers/index.js
  src/helpers/url.js
Labels: bug

#854 fix: remove file upload restraint from contents modal if modules are allowed
  RELEASE.md
  src/customizations/volto/components/manage/Contents/ContentsUploadModal.jsx
Labels: enhancement

#857 chore: porting from 11.x.x and fix merge conflicts
  src/components/ImageWithErrors/ImageWithErrors.jsx
  src/config/italiaConfig.js
  src/helpers/images.js
  src/helpers/index.js
  src/helpers/url.js
Labels: bug

#856 fix: select input a11y
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/SelectInput/SelectInput.jsx
Labels: bug, a11y-accessibility
