Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-09, with the labels that each got.

#983 chore: updated volto form block 3.13.0
  package.json
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/SelectFilter.jsx
  yarn.lock
Labels: rer

#997 fix: read more a11y
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
  src/components/ItaliaTheme/Blocks/Listing/SimpleCard/Card/SimpleCardDefault.jsx
  src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/BandiInEvidenceTemplateSkeleton.jsx
Labels: a11y-accessibility, rer

#998 fix: card with slide text a11y
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
Labels: a11y-accessibility, rer

#994 chore: updated text, select and date input filter with label props
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/DateFilter.jsx
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/SelectFilter.jsx
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/TextFilter.jsx
  src/components/SelectInput/SelectInput.jsx
  src/theme/ItaliaTheme/Blocks/common/_searchBlockFilters.scss
Labels: a11y-accessibility
