Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-10, with the labels that each got.

#970 chore: updated volto-blocks-widget v3.4.7
  package.json
  yarn.lock
Labels: rer, major-deps-upgrade

#1010 chore: updated warning form block message and configured alert with thank-you message
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/config/italiaConfig.js
  src/customizations/volto-form-block/components/FormResult.jsx
  src/overrideTranslations.jsx
Labels: missing-changelog

#1007 feat: made data_inizio_incarico conditional
  RELEASE.md
  src/components/ItaliaTheme/index.js
  src/components/ItaliaTheme/manage/Widgets/ConditionallyRequiredDateWidget.jsx
  src/config/Widgets/widgets.js
Labels: porting-needed
