Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-07, with the labels that each got.

#963 fix: style for fieldlabel removed and moved inside the addon
  package.json
  src/theme/ItaliaTheme/Components/_customerSatisfaction.scss
  yarn.lock
Labels: rer

#967 fix: add role='menuitem' to links inside dropdown to fix menubar role hierarchy
  src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx
Labels: a11y-accessibility

#976 chore: updated requestTimeout with adBlock message
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/customizations/volto/components/theme/RequestTimeout/RequestTimeout.jsx
  src/overrideTranslations.jsx
Labels: v2
