Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-04, with the labels that each got.

#920 update release.md
  RELEASE.md
Labels: waiting-be

#922 update release.md
  RELEASE.md
Labels: waiting-be

#926 fix: regex for fragments in formValidation
  RELEASE.md
  src/components/__tests__/FormValidation.test.js
  src/customizations/volto/helpers/FormValidation/FormValidation.js
Labels: porting-needed

#912 fix: added label to TextFilter component
  RELEASE.md
  src/components/ItaliaTheme/Blocks/Common/SearchFilters/TextFilter.jsx
  src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
Labels: a11y-accessibility

#929 feat: optionally hide Site Title from control panel
  RELEASE.md
  src/components/ItaliaTheme/BrandText/BrandText.jsx
Labels: rer

#935 Us 65355 teaser block
  RELEASE.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/ItaliaTheme/Blocks/Teaser/ItaliaTeaserBody.jsx
  src/components/ItaliaTheme/Blocks/Teaser/schema.js
  src/components/ItaliaTheme/Icons/common/common.js
  src/config/Blocks/blocks.js
  src/config/italiaConfig.js
  src/customizations/volto/components/manage/Blocks/Teaser/Body.jsx
  src/customizations/volto/components/manage/Widgets/ObjectBrowserWidget.jsx
  src/overrideTranslations.jsx
Labels: enhancement, waiting-be, porting-needed

#943 fix: multiple query widget paths
  package.json
  yarn.lock
Labels: rer
