Repository RedTurtle/design-comuni-plone-theme, pull requests merged in 2025-03, with the labels that each got.

#897 Bug 65273 feedback noncontentroutes
  package.json
  src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
  src/config/italiaConfig.js
  src/customizations/volto/components/theme/Footer/Footer.jsx
  yarn.lock
Labels: porting-needed

#898 fix: search block focus styles and scroll into view results when apply filters
  RELEASE.md
  src/customizations/volto/components/manage/Blocks/Search/SearchBlockView.jsx
  src/customizations/volto/components/manage/Blocks/Search/layout/LeftColumnFacets.jsx
  src/customizations/volto/components/manage/Blocks/Search/layout/RightColumnFacets.jsx
  src/theme/ItaliaTheme/Blocks/_search.scss
  src/theme/bootstrap-override/_bootstrap-italia-site.scss
  src/theme/bootstrap-override/bootstrap-italia/_form-select.scss
Labels: rer

#899 fix: added h tags for icons and numbers block
  src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
  src/components/ItaliaTheme/Blocks/IconBlocks/View.jsx
  src/components/ItaliaTheme/Blocks/NumbersBlock/View.jsx
  src/theme/ItaliaTheme/Blocks/_iconBlocks.scss
  src/theme/ItaliaTheme/Blocks/_numbers.scss
Labels: rer

#908 fix: toggle accordion on link inside click
  src/components/ItaliaTheme/Blocks/Accordion/Block/ViewBlock.jsx
Labels: rer

#906 fix: a11y bando and events timeline
  RELEASE.md
  src/components/ItaliaTheme/View/Commons/BandoDates.jsx
  src/components/ItaliaTheme/View/Commons/Dates.jsx
Labels: rer

#907 fix: Blockquote a11y
  RELEASE.md
  src/config/Slate/Blockquote/index.js
  src/theme/ItaliaTheme/_main.scss
Labels: rer

#905 Us 58852 h1 display none fix v3
  RELEASE.md
  src/theme/ItaliaTheme/_home.scss
Labels: a11y-accessibility, rer

#904 fix: changed homepage h1 from display none to visually hidden
  RELEASE.md
  src/theme/ItaliaTheme/_home.scss
Labels: a11y-accessibility, rer

#903 feat: Page placeholder HeaderEnd
  src/components/ItaliaTheme/View/PageView/PageView.jsx
  src/components/ItaliaTheme/View/PageView/Placeholder/HeaderEnd.jsx
  src/components/ItaliaTheme/View/index.js
Labels: rer

#900 fix: riportate sul file le modifiche fatte su Volto 18 per il componente HtmlSlateWidget
  RELEASE.md
  src/components/ItaliaTheme/manage/Widgets/HtmlSlateWidget.jsx
Labels: a11y-accessibility, rer

#901 fix: Fix grid listing on mobile
  RELEASE.md
  src/theme/ItaliaTheme/Blocks/_gridBlock.scss
Labels: rer

#914 fix: handle slash in search params in url regex
  RELEASE.md
  src/components/__tests__/FormValidation.test.js
  src/customizations/volto/helpers/FormValidation/FormValidation.js
Labels: porting-needed

#919 fix: link view redirects when user cannot edit, also redirects server side
  RELEASE.md
  src/customizations/volto/components/theme/View/LinkView.jsx
Labels: porting-needed

#915 fix: focus of buttons + focus of inputs + contrast of buttons
  RELEASE.md
  src/components/ItaliaTheme/ScrollToTop/ScrollToTop.jsx
  src/theme/ItaliaTheme/_common.scss
  src/theme/bootstrap-override/bootstrap-italia/_buttons.scss
  src/theme/bootstrap-override/bootstrap-italia/_focus.scss
  src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss
Labels: a11y-accessibility

#916 fix: focus of buttons + focus of inputs + contrast of buttons
  RELEASE.md
  src/components/ItaliaTheme/ScrollToTop/ScrollToTop.jsx
  src/theme/ItaliaTheme/_common.scss
  src/theme/bootstrap-override/bootstrap-italia/_buttons.scss
  src/theme/bootstrap-override/bootstrap-italia/_focus.scss
  src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss
Labels: a11y-accessibility

#921 fix: document cards layout for ct persona
  src/components/ItaliaTheme/View/PersonaView/PersonaDocumenti.jsx
Labels: porting-needed

#924 fix: rollback volto-blocks-editor to a compatible version, fix volto-blocks-editor text block is always slate in it's block chooser
  RELEASE.md
  package.json
  src/config/italiaConfig.js
  yarn.lock
Labels: bug, dependencies
